// Auto-generated by scripts/download-images.mjs
export type ImageSlot = (typeof imageSlots)[number]['slot'];

export const imageSlots = [
  {
    "slot": "hero-painting",
    "alt": "Colorful paint rollers — professional painting service"
  },
  {
    "slot": "service-interior",
    "alt": "Modern interior room freshly painted"
  },
  {
    "slot": "service-exterior",
    "alt": "Painter applying paint to an exterior wall"
  },
  {
    "slot": "service-villa",
    "alt": "Luxury villa exterior with manicured lawn"
  },
  {
    "slot": "service-apartment",
    "alt": "Modern apartment living room interior"
  },
  {
    "slot": "service-commercial",
    "alt": "Modern office workspace interior"
  },
  {
    "slot": "service-decorative",
    "alt": "Decorative textured wall finish close-up"
  },
  {
    "slot": "area-dubai-marina",
    "alt": "Dubai Marina skyline with yacht harbour"
  },
  {
    "slot": "area-downtown-dubai",
    "alt": "Downtown Dubai skyline with Burj Khalifa"
  },
  {
    "slot": "area-palm-jumeirah",
    "alt": "Aerial view of Palm Jumeirah"
  },
  {
    "slot": "area-jumeirah",
    "alt": "Modern villa exterior in Jumeirah"
  },
  {
    "slot": "area-business-bay",
    "alt": "Dubai high-rise residential buildings"
  },
  {
    "slot": "area-jlt",
    "alt": "Dubai lake-front tower cluster"
  },
  {
    "slot": "area-arabian-ranches",
    "alt": "Suburban villa community at dusk"
  },
  {
    "slot": "area-mirdif",
    "alt": "Family villa exterior with garden"
  },
  {
    "slot": "area-jvc",
    "alt": "Modern townhouse row in Dubai"
  },
  {
    "slot": "vendor-elite",
    "alt": "Premium interior with decorative wall finish"
  },
  {
    "slot": "vendor-royal",
    "alt": "Bright modern apartment after repaint"
  },
  {
    "slot": "vendor-sahara",
    "alt": "Modern villa exterior freshly repainted"
  },
  {
    "slot": "vendor-crown",
    "alt": "Decorative Marmorino feature wall"
  }
] as const;

const altBySlot: Record<string, string> = Object.fromEntries(imageSlots.map((i) => [i.slot, i.alt]));
export const altFor = (slot: string) => altBySlot[slot] ?? '';

const serviceSlotMap: Record<string, string> = {
  'interior-painting': 'service-interior',
  'exterior-painting': 'service-exterior',
  'villa-painting': 'service-villa',
  'apartment-painting': 'service-apartment',
  'commercial-painting': 'service-commercial',
  'texture-decorative': 'service-decorative',
};

const vendorSlotMap: Record<string, string> = {
  'elite-painters-dubai': 'vendor-elite',
  'royal-finish-llc': 'vendor-royal',
  'sahara-coats': 'vendor-sahara',
  'crown-decor-painting': 'vendor-crown',
};

export const imageForArea = (slug: string) => `area-${slug}`;
export const imageForService = (slug: string) => serviceSlotMap[slug] ?? 'service-interior';
export const imageForVendor = (slug: string) => vendorSlotMap[slug] ?? 'vendor-elite';

export const imageExistsForArea = (slug: string) =>
  ['dubai-marina', 'downtown-dubai', 'palm-jumeirah', 'jumeirah', 'business-bay', 'jlt', 'arabian-ranches', 'mirdif', 'jvc'].includes(slug);

export const imageUrl = (siteUrl: string, slot: string, ext: 'jpg' | 'webp' = 'jpg') =>
  `${siteUrl}/images/${slot}.${ext}`;
